name: "Crawl builds"

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: |
          bun ci
          if bun run src/crawler.ts
          then
            rm -rf previous
            mv data previous
          fi
      - uses: stefanzweifel/git-auto-commit-action@v4
