name: "Crawl builds"

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  crawl:
    runs-on: ubuntu-latest
    env:
      POESESSID: ${{ secrets.POESESSID }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: |
          mkdir -p mods data
          bun run src/parseMods.ts &

          if bun run src/modPrices.ts
          then
            rm -rf previous-mods
            mv mods previous-mods
          fi &

          if bun run src/crawler.ts
          then
            rm -rf previous
            mv data previous
          fi

          wait
      - uses: stefanzweifel/git-auto-commit-action@v4
